a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("The addition of a and b is :", a+b)
print("The subtraction of a and b is :", a-b)
print("The division of a and b is :", a/b)
print("The multiplication of a and b is :", a*b)
print("The module of a and b is : ", a%b)